# Generated by Django 2.1.1 on 2018-12-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.TextField(verbose_name='Dni'),
        ),
    ]
