# Generated by Django 2.1.1 on 2018-12-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20181208_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.TextField(verbose_name='Número de Contacto'),
        ),
    ]
