# Generated by Django 2.1.1 on 2018-10-08 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('sinopsis', models.TextField(default='', verbose_name='Ingrese una breve sinopsis del Videojuego')),
                ('categoria', models.CharField(max_length=200, verbose_name='Categoria')),
                ('FechaLanzamiento', models.DateField(verbose_name='Año de lanzamiento')),
                ('image', models.ImageField(upload_to='image_juegos', verbose_name='Imagen')),
                ('duracionPromedio', models.CharField(max_length=200, verbose_name='Duracion Promedio del videojuego')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'videojuego',
                'verbose_name_plural': 'catalogopersonal',
                'ordering': ['created'],
            },
        ),
    ]
