# Generated by Django 2.1.1 on 2018-12-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_personal', '0005_auto_20181103_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
