# Generated by Django 2.1.1 on 2018-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_personal', '0006_videojuegos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='Descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videojuegos',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
