# Generated by Django 2.1.1 on 2018-11-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='owner_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
