# Generated by Django 2.1.1 on 2018-11-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_personal', '0005_auto_20181103_1134'),
        ('catalogo_general', '0002_auto_20181118_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='votacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_votacion', models.IntegerField()),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_personal.Videojuegos')),
            ],
            options={
                'verbose_name': 'votacion',
                'verbose_name_plural': 'votaciones',
            },
        ),
    ]
