# Generated by Django 2.1.1 on 2018-12-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_general', '0004_notificaciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificaciones',
        ),
    ]
