# Generated by Django 2.1.1 on 2018-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_general', '0006_notificacionesventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionesventas',
            name='estado',
            field=models.IntegerField(null=True),
        ),
    ]
